-- ============================================================
-- NEMESIS Reservations Platform — Reference schema (PostgreSQL 16)
-- ============================================================
-- This file is a REFERENCE, not the source of truth. The source of truth
-- is the Laravel migrations in database/migrations/ — this file documents
-- what those migrations produce, for ERD tools, DBA review, or spinning up
-- a database by hand. Every migration should keep this file in sync.
--
-- Framework-managed tables (sessions, cache, jobs, password_reset_tokens,
-- personal_access_tokens, migrations) are generated by Laravel's own
-- default migrations and are NOT redefined here.
-- ============================================================

BEGIN;

-- ── restaurants ────────────────────────────────────────────
-- Single row per deployed instance (one instance per client — see
-- docs/00-PRODUCT-SPEC.md §1).
CREATE TABLE restaurants (
    id                  BIGSERIAL PRIMARY KEY,
    name                VARCHAR(120) NOT NULL,
    tagline             VARCHAR(160),
    email               VARCHAR(160),
    phone               VARCHAR(40),
    address             VARCHAR(255),
    timezone            VARCHAR(60)  NOT NULL DEFAULT 'Africa/Harare',
    currency            VARCHAR(3)   NOT NULL DEFAULT 'USD',
    seats               INTEGER      NOT NULL DEFAULT 0,
    tables_count        INTEGER      NOT NULL DEFAULT 0,
    logo_path           VARCHAR(255),
    primary_color_hex   VARCHAR(7)   NOT NULL DEFAULT '#C9A227',
    created_at          TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP(0) NOT NULL DEFAULT now()
);

-- ── restaurant_hours ───────────────────────────────────────
-- 7 rows per restaurant (one per weekday, 0=Monday .. 6=Sunday).
CREATE TABLE restaurant_hours (
    id              BIGSERIAL PRIMARY KEY,
    restaurant_id   BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    day_of_week     SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    open_time       TIME,
    close_time      TIME,
    is_closed       BOOLEAN NOT NULL DEFAULT false,
    UNIQUE (restaurant_id, day_of_week)
);

-- ── restaurant_rules ───────────────────────────────────────
-- Single row per restaurant.
CREATE TABLE restaurant_rules (
    id                          BIGSERIAL PRIMARY KEY,
    restaurant_id               BIGINT NOT NULL UNIQUE REFERENCES restaurants(id) ON DELETE CASCADE,
    max_party_size              INTEGER NOT NULL DEFAULT 14,
    slot_length_minutes         INTEGER NOT NULL DEFAULT 90,
    buffer_minutes              INTEGER NOT NULL DEFAULT 15,
    cancellation_window_hours   INTEGER NOT NULL DEFAULT 4,
    deposit_required_above      INTEGER
);

-- ── users ──────────────────────────────────────────────────
-- Staff accounts. Real bcrypt-hashed passwords via Laravel's Hash facade.
CREATE TABLE users (
    id                  BIGSERIAL PRIMARY KEY,
    restaurant_id       BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    name                VARCHAR(120) NOT NULL,
    email               VARCHAR(160) NOT NULL UNIQUE,
    email_verified_at   TIMESTAMP(0),
    password            VARCHAR(255) NOT NULL,
    role                VARCHAR(20) NOT NULL DEFAULT 'host'
                         CHECK (role IN ('owner', 'manager', 'host')),
    avatar_initials     VARCHAR(4),
    last_login_at       TIMESTAMP(0),
    remember_token      VARCHAR(100),
    created_at          TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP(0) NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_restaurant ON users (restaurant_id);

-- ── tables ─────────────────────────────────────────────────
-- Floor plan. "tables" is a reserved-ish word in some tooling but valid in
-- Postgres — Laravel's migration would name the model `RestaurantTable`
-- mapped to this table if you want to avoid ORM ambiguity; either works.
CREATE TABLE tables (
    id              BIGSERIAL PRIMARY KEY,
    restaurant_id   BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    code            VARCHAR(10) NOT NULL,
    zone            VARCHAR(60),
    capacity        INTEGER NOT NULL,
    shape           VARCHAR(10) NOT NULL DEFAULT 'square'
                    CHECK (shape IN ('round', 'square', 'rect')),
    pos_x           DECIMAL(5,2) NOT NULL DEFAULT 0,
    pos_y           DECIMAL(5,2) NOT NULL DEFAULT 0,
    status          VARCHAR(20) NOT NULL DEFAULT 'Available'
                    CHECK (status IN ('Available', 'Occupied', 'Reserved', 'Cleaning')),
    deleted_at      TIMESTAMP(0),
    created_at      TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP(0) NOT NULL DEFAULT now(),
    UNIQUE (restaurant_id, code)
);

CREATE INDEX idx_tables_restaurant ON tables (restaurant_id) WHERE deleted_at IS NULL;

-- ── customers ──────────────────────────────────────────────
CREATE TABLE customers (
    id               BIGSERIAL PRIMARY KEY,
    restaurant_id    BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    name             VARCHAR(120) NOT NULL,
    email            VARCHAR(160),
    phone            VARCHAR(40) NOT NULL,
    visits           INTEGER NOT NULL DEFAULT 0,
    last_visit_at    DATE,
    is_vip           BOOLEAN NOT NULL DEFAULT false,
    lifetime_spend   DECIMAL(10,2) NOT NULL DEFAULT 0,
    deleted_at       TIMESTAMP(0),
    created_at       TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP(0) NOT NULL DEFAULT now()
);

CREATE INDEX idx_customers_restaurant ON customers (restaurant_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_customers_search ON customers (restaurant_id, name, email);

-- ── customer_preferences ──────────────────────────────────
CREATE TABLE customer_preferences (
    id            BIGSERIAL PRIMARY KEY,
    customer_id   BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    note          VARCHAR(160) NOT NULL
);

CREATE INDEX idx_customer_preferences_customer ON customer_preferences (customer_id);

-- ── reservations ───────────────────────────────────────────
CREATE TABLE reservations (
    id                    BIGSERIAL PRIMARY KEY,
    restaurant_id         BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    public_ref            VARCHAR(20) NOT NULL,
    customer_id           BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    table_id              BIGINT REFERENCES tables(id) ON DELETE SET NULL,
    guest_name            VARCHAR(120) NOT NULL,
    guest_phone           VARCHAR(40) NOT NULL,
    guest_email           VARCHAR(160),
    date                  DATE NOT NULL,
    time                  TIME NOT NULL,
    party_size            INTEGER NOT NULL,
    status                VARCHAR(20) NOT NULL DEFAULT 'Upcoming'
                          CHECK (status IN ('Upcoming', 'Confirmed', 'Completed', 'Cancelled')),
    notes                 TEXT,
    source                VARCHAR(20) NOT NULL DEFAULT 'App'
                          CHECK (source IN ('Website', 'Phone', 'App', 'Walk-in')),
    created_by_user_id    BIGINT REFERENCES users(id) ON DELETE SET NULL,
    deleted_at            TIMESTAMP(0),
    created_at            TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP(0) NOT NULL DEFAULT now(),
    UNIQUE (restaurant_id, public_ref)
);

-- The conflict-detection query (same table, overlapping time window, same
-- date, not cancelled) is the single most frequent query in the whole
-- system — this composite index is load-bearing.
CREATE INDEX idx_reservations_conflict_check
    ON reservations (restaurant_id, date, table_id, status)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_reservations_status
    ON reservations (restaurant_id, status)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_reservations_customer ON reservations (customer_id);

-- ── waitlist ───────────────────────────────────────────────
CREATE TABLE waitlist (
    id                      BIGSERIAL PRIMARY KEY,
    restaurant_id           BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    name                    VARCHAR(120) NOT NULL,
    phone                   VARCHAR(40) NOT NULL,
    party_size              INTEGER NOT NULL,
    quoted_wait_minutes     INTEGER,
    notes                   VARCHAR(255),
    status                  VARCHAR(10) NOT NULL DEFAULT 'Waiting'
                            CHECK (status IN ('Waiting', 'Seated', 'Left')),
    added_at                TIMESTAMP(0) NOT NULL DEFAULT now()
);

CREATE INDEX idx_waitlist_restaurant ON waitlist (restaurant_id, status);

-- ── notifications ──────────────────────────────────────────
CREATE TABLE notifications (
    id               BIGSERIAL PRIMARY KEY,
    restaurant_id    BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    title            VARCHAR(160) NOT NULL,
    message          VARCHAR(255) NOT NULL,
    is_read          BOOLEAN NOT NULL DEFAULT false,
    created_at       TIMESTAMP(0) NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_unread
    ON notifications (restaurant_id, is_read)
    WHERE is_read = false;

-- ── activity_log ───────────────────────────────────────────
-- Serves both the trimmed "recent activity" feed (query with LIMIT 12)
-- and the full, unbounded audit log (Settings → Audit log, owner-only).
CREATE TABLE activity_log (
    id                 BIGSERIAL PRIMARY KEY,
    restaurant_id      BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    actor_user_id      BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_label        VARCHAR(120) NOT NULL,
    icon               VARCHAR(40) NOT NULL DEFAULT 'bi-info-circle',
    tone               VARCHAR(10) NOT NULL DEFAULT 'slate'
                       CHECK (tone IN ('gold', 'emerald', 'rust', 'slate')),
    description        VARCHAR(255) NOT NULL,
    entity_type        VARCHAR(40),
    entity_id          BIGINT,
    created_at         TIMESTAMP(0) NOT NULL DEFAULT now()
);

CREATE INDEX idx_activity_log_restaurant_recent
    ON activity_log (restaurant_id, created_at DESC);

CREATE INDEX idx_activity_log_entity
    ON activity_log (entity_type, entity_id);

-- ── email_templates ────────────────────────────────────────
CREATE TABLE email_templates (
    id               BIGSERIAL PRIMARY KEY,
    restaurant_id    BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    key              VARCHAR(40) NOT NULL
                     CHECK (key IN ('confirm', 'reminder', 'cancel', 'vip')),
    name             VARCHAR(120) NOT NULL,
    subject          VARCHAR(160) NOT NULL,
    body             TEXT NOT NULL,
    UNIQUE (restaurant_id, key)
);

COMMIT;

-- ============================================================
-- Notes
-- ============================================================
-- 1. Every CHECK-constrained "enum" column above (role, shape, status,
--    source, tone, key) is exactly what Laravel's `$table->enum(...)`
--    produces on a Postgres driver — a VARCHAR + CHECK constraint, not a
--    native Postgres ENUM type. This is intentional: native Postgres enums
--    are painful to alter later (ADD VALUE has transaction restrictions);
--    CHECK constraints are trivially altered in a new migration.
--
-- 2. Soft deletes (`deleted_at`) exist on tables, customers, reservations
--    only — the three entities where "oops, undo" or historical integrity
--    genuinely matters. Everything else (notifications, activity_log,
--    waitlist) is either ephemeral or intentionally append-only.
--
-- 3. `restaurants.id` is NOT a foreign key on every other table by
--    accident of copy-paste — it's deliberate. Even though this is a
--    single-restaurant-per-database deployment model (docs/00 §1), every
--    table still carries restaurant_id. This keeps every query pattern
--    consistent and means that IF a future version ever needs to merge
--    two client databases (e.g. a client with two locations wants one
--    login), the schema already supports it without a redesign.
-- ============================================================
